workflows:
  pr-flutter-tests:
    triggering:
      events:
        - pull_request
      branch_patterns:
        - pattern: '*'
          include: true
          source: false
    name: Pull Request Checks
    environment:
      flutter: 3.35.0
      xcode: 16.2
      cocoapods: 1.16.2
    scripts:    
      - name: Get dependencies
        script: |
          echo "Get dependencies"
          flutter packages pub get
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Run Flutter tests
        script: |
          flutter test